preload = ["@ecopages/bun-postcss-loader", "@ecopages/bun-mdx-kitajs-loader"]

[test]
preload = [
  "./scripts/setup-test.ts",
  "@ecopages/bun-postcss-loader",
  "@ecopages/bun-mdx-kitajs-loader",
]

[install.scopes]
"@jsr" = "https://npm.jsr.io"

[install]
linker = "hoisted"
