preload = ["@ecopages/bun-postcss-loader"]

[test]
preload = [
  "./scripts/setup-test.ts",
  "@ecopages/bun-postcss-loader",
]
exclude = ["**/*.test.browser.ts"]

[install.scopes]
"@jsr" = "https://npm.jsr.io"

[install]
linker = "hoisted"
